config/routes.rb
Mitsumoritaro::Application.routes.draw do
  resources :template_tasks do
    member do
      patch 'move_higher' => 'template_tasks#move_higher', as: :move_higher
      patch 'move_lower' => 'template_tasks#move_lower', as: :move_lower
    end
  end

  resources :projects do
    collection do
      get 'archived' => 'projects#archived', as: :archived
    end
    member do
      post 'dup' => 'projects#dup_form', as: :dup
      post 'archive' => 'projects#archive', as: :archive
      post 'active' => 'projects#active', as: :active
    end
    resources :additional_costs do
      member do
        patch 'move_higher' => 'additional_costs#move_higher', as: :move_higher
        patch 'move_lower' => 'additional_costs#move_lower', as: :move_lower
      end
    end
    resource :dashboard, only: :show do
      member do
        get 'archived' => 'dashboards#archived', as: :archived
        get 'convert' => 'dashboards#convert', as: :convert
      end
    end
    resources :project_tasks, except: %i[show new edit] do
      member do
        get 'move_higher' => 'project_tasks#move_higher', as: :move_higher
        get 'move_lower' => 'project_tasks#move_lower', as: :move_lower
      end
    end
    resources :categories, only: %i[create update destroy], controller: :items do
      member do
        get 'move_higher' => 'items#move_higher', as: :move_higher
        get 'move_lower' => 'items#move_lower', as: :move_lower
        post 'copy' => 'items#copy', as: :copy
      end
      resources :sub_categories, only: %i[create update destroy] , controller: :items do
        member do
          get 'move_higher' => 'items#move_higher', as: :move_higher
          get 'move_lower' =>  'items#move_lower', as: :move_lower
          post 'copy' => 'items#copy', as: :copy
        end
        resources :stories, only: %i[create update destroy] , controller: :items do
          member do
            get 'move_higher' => 'items#move_higher', as: :move_higher
            get 'move_lower' => 'items#move_lower', as: :move_lower
            post 'copy' => 'items#copy', as: :copy
          end
          resources :task_points, only: %i[create destroy]
        end
      end
    end
  end

  namespace :api do
    resources :projects, only: %i[show create update] do
      resources :categories, except: %i[index new edit] do
        member do
          patch 'move_higher' => 'categories#move_higher', as: :move_higher
          patch 'move_lower' => 'categories#move_lower', as: :move_lower
        end
        resources :sub_categories, except: %i[index new edit] do
          member do
            patch 'move_higher' => 'sub_categories#move_higher', as: :move_higher
            patch 'move_lower' => 'sub_categories#move_lower', as: :move_lower
          end
          resources :stories, except: %i[index new edit] do
            member do
              patch 'move_higher' => 'stories#move_higher', as: :move_higher
              patch 'move_lower' => 'stories#move_lower', as: :move_lower
            end
            resources :task_points, only: %i[create destroy]
          end
        end
      end
    end
  end

  root :to => 'projects#index'

end

app/models/additional_cost.rb
class AdditionalCost < ActiveRecord::Base
  belongs_to :project
  acts_as_list scope: :project
  validates :name, :price, presence: true
end

app/controllers/additional_costs_controller.rb
class AdditionalCostsController < ApplicationController
  before_filter :set_project_to_variable
  def index
    @additional_costs = @project.additional_costs
  end

  def new
    @additional_cost = @project.additional_costs.build
  end

  def edit
    @additional_cost = @project.additional_costs.find params[:id]
  end

  def create
    @additional_cost = @project.additional_costs.build(permitted_params_for_additional_cost)
    @additional_cost.save!
    redirect_to project_additional_costs_url(@project)
  rescue ActiveRecord::RecordInvalid => e
    render 'new'
  end

  def update
    @additional_cost = @project.additional_costs.find params[:id]
    @additional_cost.update_attributes!(permitted_params_for_additional_cost)
    redirect_to project_additional_costs_url(@project)
  rescue ActiveRecord::RecordInvalid => e
    render 'edit'
  end

  def destroy
    @project.additional_costs.find(params[:id]).destroy
    redirect_to project_additional_costs_url(@project)
  end

  def move_higher
    move(:move_higher)
  end

  def move_lower
    move(:move_lower)
  end

  private
  def move(direction)
    @project.additional_costs.find(params[:id]).send(direction)
    redirect_to project_additional_costs_url(@project)
  end

  def set_project_to_variable
    @project = Project.find(params[:project_id])
  end

  def permitted_params_for_additional_cost
    params.require(:additional_cost).permit(:name, :price, :remarks)
  end
end

app/helpers/additional_costs_helper.rb
module AdditionalCostsHelper
end

app/views/additional_costs/_form.html.haml
= simple_form_for [@project, @additional_cost] do |f|
  = f.input :name
  = f.input :price
  = f.input :remarks
  = f.button :submit, class: %i(btn btn-primary)
  = link_to t('.cancel', :default => t("helpers.links.cancel")), project_additional_costs_path(@project), :class => 'btn btn-default'

app/views/additional_costs/edit.html.haml
- model_class = AdditionalCost
.page-header
  %h1= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => 'form'

app/views/additional_costs/index.html.haml
- model_class = AdditionalCost
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:price)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @additional_costs.each_with_index do |ac, i|
      %tr
        %td
          = ac.name
          = link_to_if(i != 0, '↑', move_higher_project_additional_cost_path(@project, ac), method: :patch) { }
          = link_to_if(@additional_costs.size != i + 1, '↓', move_lower_project_additional_cost_path(@project, ac), method: :patch) { }
        %td= number_with_delimiter(ac.price)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_additional_cost_path(@project, ac), :class => 'btn btn-default btn-sm'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), project_additional_cost_path(@project, ac), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-sm btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_project_additional_cost_path, :class => 'btn btn-primary'

app/views/additional_costs/new.html.haml
- model_class = AdditionalCost
.page-header
  %h1= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => 'form'