config/routes.rb
Mitsumoritaro::Application.routes.draw do
  resources :template_tasks do
    member do
      patch 'move_higher' => 'template_tasks#move_higher', as: :move_higher
      patch 'move_lower' => 'template_tasks#move_lower', as: :move_lower
    end
  end

  resources :projects do
    collection do
      get 'archived' => 'projects#archived', as: :archived
    end
    member do
      post 'dup' => 'projects#dup_form', as: :dup
      post 'archive' => 'projects#archive', as: :archive
      post 'active' => 'projects#active', as: :active
    end
    resources :additional_costs do
      member do
        patch 'move_higher' => 'additional_costs#move_higher', as: :move_higher
        patch 'move_lower' => 'additional_costs#move_lower', as: :move_lower
      end
    end
    resource :dashboard, only: :show do
      member do
        get 'archived' => 'dashboards#archived', as: :archived
        get 'convert' => 'dashboards#convert', as: :convert
      end
    end
    resources :project_tasks, except: %i[show new edit] do
      member do
        get 'move_higher' => 'project_tasks#move_higher', as: :move_higher
        get 'move_lower' => 'project_tasks#move_lower', as: :move_lower
      end
    end
    resources :categories, only: %i[create update destroy], controller: :items do
      member do
        get 'move_higher' => 'items#move_higher', as: :move_higher
        get 'move_lower' => 'items#move_lower', as: :move_lower
        post 'copy' => 'items#copy', as: :copy
      end
      resources :sub_categories, only: %i[create update destroy] , controller: :items do
        member do
          get 'move_higher' => 'items#move_higher', as: :move_higher
          get 'move_lower' =>  'items#move_lower', as: :move_lower
          post 'copy' => 'items#copy', as: :copy
        end
        resources :stories, only: %i[create update destroy] , controller: :items do
          member do
            get 'move_higher' => 'items#move_higher', as: :move_higher
            get 'move_lower' => 'items#move_lower', as: :move_lower
            post 'copy' => 'items#copy', as: :copy
          end
          resources :task_points, only: %i[create destroy]
        end
      end
    end
  end

  namespace :api do
    resources :projects, only: %i[show create update] do
      resources :categories, except: %i[index new edit] do
        member do
          patch 'move_higher' => 'categories#move_higher', as: :move_higher
          patch 'move_lower' => 'categories#move_lower', as: :move_lower
        end
        resources :sub_categories, except: %i[index new edit] do
          member do
            patch 'move_higher' => 'sub_categories#move_higher', as: :move_higher
            patch 'move_lower' => 'sub_categories#move_lower', as: :move_lower
          end
          resources :stories, except: %i[index new edit] do
            member do
              patch 'move_higher' => 'stories#move_higher', as: :move_higher
              patch 'move_lower' => 'stories#move_lower', as: :move_lower
            end
            resources :task_points, only: %i[create destroy]
          end
        end
      end
    end
  end

  root :to => 'projects#index'

end

app/models/project.rb
# -*- coding: utf-8 -*-
class Project < ActiveRecord::Base
  has_many :categories, -> { order(:position) }, dependent: :destroy
  has_many :project_tasks, -> { order(:position) }, dependent: :destroy
  has_many :additional_costs, -> { order(:position) }, dependent: :destroy
  accepts_nested_attributes_for :project_tasks, allow_destroy: true
  validates :name, presence: true

  def sum_of_point_50
    categories.map(&:sum_of_point_50).inject(0, :+)
  end

  def sum_of_point_50_by_project_task_id(project_task_id)
    categories.map{|l| l.sum_of_point_50_by_project_task_id(project_task_id) }.inject(0, :+)
  end

  def sum_of_square_of_diff
    categories.map(&:sum_of_square_of_diff).inject(0, :+)
  end

  def buffer
    Math::sqrt(sum_of_square_of_diff)
  end

  def total_price_with_buffer
    ratio = 1.0 + buffer / sum_of_point_50
    categories.map{|c| c.total_price(ratio, days_per_point)}.inject(0, :+)
  end

  def total_price_50
    ratio = 1.0
    categories.map{|c| c.total_price(ratio, days_per_point)}.inject(0, :+)
  end

  def dup_deep!
    proj = dup_project!
    dup_additional_costs!(proj)
    project_task_id_map = dup_project_tasks!(proj)
    dup_categories_deep!(proj, project_task_id_map)

    proj
  end

  def dup_project!
    proj = dup
    proj.name += ' (コピー)'
    proj.archived = false
    proj.save!
    proj
  end

  def dup_additional_costs!(proj)
    additional_costs.each do |orig_ac|
      proj.additional_costs << orig_ac.dup
    end
    proj.save!
    proj
  end

  def dup_project_tasks!(new_proj)
    project_task_id_map = {}
    project_tasks.each do |orig_pt|
      pt = orig_pt.dup
      pt.project = new_proj
      pt.save!
      project_task_id_map[orig_pt.id] = pt.id
    end
    project_task_id_map
  end

  def org_project_task_id_map
    project_task_id_map = {}
    project_tasks.each do |orig_pt|
      project_task_id_map[orig_pt.id] = orig_pt.id
    end
    project_task_id_map
  end

  def dup_categories_deep!(new_proj, project_task_id_map)
    categories.each do |orig_cat|
      new_proj.categories << orig_cat.dup_deep(project_task_id_map)
    end
    new_proj.save!
  end

  def add_default_project_tasks
    default_tasks = TemplateTask.where(default_task: true).order(:position)
    default_tasks.each do |default_task|
      self.project_tasks.build(name: default_task.name, price_per_day: default_task.price_per_day)
    end
  end

  def archive!
    self.update!(archived: true)
  end

  def active!
    self.update!(archived: false)
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  def show
    render json: Project.find(params[:id]).as_json(include: [{ categories: { include: {sub_categories: { include: { stories: { include: :task_points } } } } } }, :project_tasks, :additional_costs ] )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(archived: [nil, false])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(permitted_params_for_project)
    @project.add_default_project_tasks

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(permitted_params_for_project)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to archived_projects_url }
      format.json { head :no_content }
    end
  end

  def dup_form
    orig_project = Project.find(params[:id])
    orig_project.dup_deep!

    redirect_to root_url
  end

  def archive
    @project = Project.find(params[:id])
    @project.archive!
    redirect_to root_url
  end

  def active
    @project = Project.find(params[:id])
    @project.active!
    redirect_to archived_projects_path
  end

  def archived
    @projects = Project.where(archived: true)
  end

  private

  def permitted_params_for_project
    params.require(:project).permit(:name, :days_per_point)
  end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
    <%= f.input :name %>
    <%= f.input :days_per_point %>
    <%= f.button :submit, class: %i(btn btn-primary) %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn btn-default' %>
<% end %>

app/views/projects/archived.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>Projects <small>(archived)</small></h1>
</div>
<ul class="nav nav-tabs">
  <li><%= link_to "Active", root_url %></li>
  <li class="active">
    <a href="#">Archive</a>
  </li>
</ul>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:days_per_point) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, archived_project_dashboard_path(project, anchor: "/projects/#{project.id}/dashboard/archived")  %></td>
        <td><%= project.days_per_point %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to "複製",
                      dup_project_path(project), class: 'btn btn-default btn-sm', method: :post %>
          <%= link_to active_project_path(project),
                      title: 're-open project',
                      class: 'btn btn-sm btn-info', method: :post do %>
              <i class="icon-folder-open"></i> ReOpen
          <%  end %>
          <%= link_to project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-sm btn-danger' do%>
              <i class="icon-trash"></i> <%= t('.destroy', :default => t("helpers.links.destroy"))%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
aaaaaaa sample
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">Active</a>
  </li>
  <li><%= link_to "Archive", archived_projects_path %></li>
</ul>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:days_per_point) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_dashboard_path(project, anchor: "/projects/#{project.id}/dashboard")  %></td>
        <td><%= project.days_per_point %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-default btn-sm' %>
          <%= link_to "科目設定",
                      project_project_tasks_path(project), :class => 'btn btn-default btn-sm' %>
          <%= link_to "複製",
                      dup_project_path(project), class: 'btn btn-default btn-sm', method: :post %>
          <%= link_to archive_project_path(project), :method => :post,
                      :class => 'btn btn-sm btn-warning' do %>
                <i class="icon-inbox"></i> Archive
          <%  end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @project.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:days_per_point) %>:</strong></dt>
  <dd><%= @project.days_per_point %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.go_to_project_top', :default => t("helpers.links.go_to_project_top")),
              project_dashboard_path(@project, anchor: "/projects/#{@project.id}/dashboard"), :class => 'btn btn-primary'  %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>