config/routes.rb
Mitsumoritaro::Application.routes.draw do
  resources :template_tasks do
    member do
      patch 'move_higher' => 'template_tasks#move_higher', as: :move_higher
      patch 'move_lower' => 'template_tasks#move_lower', as: :move_lower
    end
  end

  resources :projects do
    collection do
      get 'archived' => 'projects#archived', as: :archived
    end
    member do
      post 'dup' => 'projects#dup_form', as: :dup
      post 'archive' => 'projects#archive', as: :archive
      post 'active' => 'projects#active', as: :active
    end
    resources :additional_costs do
      member do
        patch 'move_higher' => 'additional_costs#move_higher', as: :move_higher
        patch 'move_lower' => 'additional_costs#move_lower', as: :move_lower
      end
    end
    resource :dashboard, only: :show do
      member do
        get 'archived' => 'dashboards#archived', as: :archived
        get 'convert' => 'dashboards#convert', as: :convert
      end
    end
    resources :project_tasks, except: %i[show new edit] do
      member do
        get 'move_higher' => 'project_tasks#move_higher', as: :move_higher
        get 'move_lower' => 'project_tasks#move_lower', as: :move_lower
      end
    end
    resources :categories, only: %i[create update destroy], controller: :items do
      member do
        get 'move_higher' => 'items#move_higher', as: :move_higher
        get 'move_lower' => 'items#move_lower', as: :move_lower
        post 'copy' => 'items#copy', as: :copy
      end
      resources :sub_categories, only: %i[create update destroy] , controller: :items do
        member do
          get 'move_higher' => 'items#move_higher', as: :move_higher
          get 'move_lower' =>  'items#move_lower', as: :move_lower
          post 'copy' => 'items#copy', as: :copy
        end
        resources :stories, only: %i[create update destroy] , controller: :items do
          member do
            get 'move_higher' => 'items#move_higher', as: :move_higher
            get 'move_lower' => 'items#move_lower', as: :move_lower
            post 'copy' => 'items#copy', as: :copy
          end
          resources :task_points, only: %i[create destroy]
        end
      end
    end
  end

  namespace :api do
    resources :projects, only: %i[show create update] do
      resources :categories, except: %i[index new edit] do
        member do
          patch 'move_higher' => 'categories#move_higher', as: :move_higher
          patch 'move_lower' => 'categories#move_lower', as: :move_lower
        end
        resources :sub_categories, except: %i[index new edit] do
          member do
            patch 'move_higher' => 'sub_categories#move_higher', as: :move_higher
            patch 'move_lower' => 'sub_categories#move_lower', as: :move_lower
          end
          resources :stories, except: %i[index new edit] do
            member do
              patch 'move_higher' => 'stories#move_higher', as: :move_higher
              patch 'move_lower' => 'stories#move_lower', as: :move_lower
            end
            resources :task_points, only: %i[create destroy]
          end
        end
      end
    end
  end

  root :to => 'projects#index'

end

app/models/template_task.rb
class TemplateTask < ActiveRecord::Base
  acts_as_list
  has_many :project_tasks, -> { order :position }
  validates :name, :price_per_day, presence: true
end

app/controllers/template_tasks_controller.rb
class TemplateTasksController < ApplicationController
  def index
    @template_tasks = TemplateTask.order(:position).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @template_tasks }
    end
  end

  # GET /template_tasks/new
  # GET /template_tasks/new.json
  def new
    @template_task = TemplateTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @template_task }
    end
  end

  # GET /template_tasks/1/edit
  def edit
    @template_task = TemplateTask.find(params[:id])
  end

  # POST /template_tasks
  # POST /template_tasks.json
  def create
    @template_task = TemplateTask.new(permitted_params_for_template_task)

    respond_to do |format|
      if @template_task.save
        format.html { redirect_to template_tasks_path, notice: 'TemplateTask was successfully created.' }
        format.json { render json: @template_task, status: :created, location: @template_task }
      else
        format.html { render action: 'new' }
        format.json { render json: @template_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /template_tasks/1
  # PUT /template_tasks/1.json
  def update
    @template_task = TemplateTask.find(params[:id])

    respond_to do |format|
      if @template_task.update_attributes(permitted_params_for_template_task)
        format.html { redirect_to template_tasks_path, notice: 'TemplateTask was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @template_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_tasks/1
  # DELETE /template_tasks/1.json
  def destroy
    @template_task = TemplateTask.find(params[:id])
    @template_task.destroy

    respond_to do |format|
      format.html { redirect_to template_tasks_url }
      format.json { head :no_content }
    end
  end

  def move_higher
    move(:move_higher)
  end

  def move_lower
    move(:move_lower)
  end

  private
  def move(direction)
    TemplateTask.find(params[:id]).send(direction)
    redirect_to template_tasks_url
  end

  def permitted_params_for_template_task
    params.require(:template_task).permit(:name, :price_per_day, :default_task)
  end
end

app/helpers/template_tasks_helper.rb
module TemplateTasksHelper
end

app/views/template_tasks/_form.html.erb
<%= simple_form_for @template_task do |f| %>
    <%= f.input :name %>
    <%= f.input :price_per_day %>
    <%= f.input :default_task %>
    <%= f.button :submit, class: %i(btn btn-primary) %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")), template_tasks_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/template_tasks/edit.html.erb
<%- model_class = TemplateTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/template_tasks/index.html.erb
<%- model_class = TemplateTask -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price_per_day) %></th>
      <th><%= model_class.human_attribute_name(:default_task) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @template_tasks.each_with_index do |template_task,i| %>
      <tr>
        <td><%= template_task.name %> <%= link_to_if(i != 0, '↑', move_higher_template_task_path(template_task), method: :patch) {} %><%= link_to_if((i < @template_tasks.size - 1), '↓', move_lower_template_task_path(template_task), method: :patch) {} %></td>
        <td><%= number_with_delimiter(template_task.price_per_day) %></td>
        <td>
          <% if template_task.default_task? %>
            <i class="fa fa-check"></i>
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                      edit_template_task_path(template_task), class: %i'btn btn-default btn-sm' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      template_task_path(template_task),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                      class: %i'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_template_task_path,
            class: %i'btn btn-primary' %>

app/views/template_tasks/new.html.erb
<%- model_class = TemplateTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>