config/routes.rb
Mitsumoritaro::Application.routes.draw do
  resources :template_tasks do
    member do
      patch 'move_higher' => 'template_tasks#move_higher', as: :move_higher
      patch 'move_lower' => 'template_tasks#move_lower', as: :move_lower
    end
  end

  resources :projects do
    collection do
      get 'archived' => 'projects#archived', as: :archived
    end
    member do
      post 'dup' => 'projects#dup_form', as: :dup
      post 'archive' => 'projects#archive', as: :archive
      post 'active' => 'projects#active', as: :active
    end
    resources :additional_costs do
      member do
        patch 'move_higher' => 'additional_costs#move_higher', as: :move_higher
        patch 'move_lower' => 'additional_costs#move_lower', as: :move_lower
      end
    end
    resource :dashboard, only: :show do
      member do
        get 'archived' => 'dashboards#archived', as: :archived
        get 'convert' => 'dashboards#convert', as: :convert
      end
    end
    resources :project_tasks, except: %i[show new edit] do
      member do
        get 'move_higher' => 'project_tasks#move_higher', as: :move_higher
        get 'move_lower' => 'project_tasks#move_lower', as: :move_lower
      end
    end
    resources :categories, only: %i[create update destroy], controller: :items do
      member do
        get 'move_higher' => 'items#move_higher', as: :move_higher
        get 'move_lower' => 'items#move_lower', as: :move_lower
        post 'copy' => 'items#copy', as: :copy
      end
      resources :sub_categories, only: %i[create update destroy] , controller: :items do
        member do
          get 'move_higher' => 'items#move_higher', as: :move_higher
          get 'move_lower' =>  'items#move_lower', as: :move_lower
          post 'copy' => 'items#copy', as: :copy
        end
        resources :stories, only: %i[create update destroy] , controller: :items do
          member do
            get 'move_higher' => 'items#move_higher', as: :move_higher
            get 'move_lower' => 'items#move_lower', as: :move_lower
            post 'copy' => 'items#copy', as: :copy
          end
          resources :task_points, only: %i[create destroy]
        end
      end
    end
  end

  namespace :api do
    resources :projects, only: %i[show create update] do
      resources :categories, except: %i[index new edit] do
        member do
          patch 'move_higher' => 'categories#move_higher', as: :move_higher
          patch 'move_lower' => 'categories#move_lower', as: :move_lower
        end
        resources :sub_categories, except: %i[index new edit] do
          member do
            patch 'move_higher' => 'sub_categories#move_higher', as: :move_higher
            patch 'move_lower' => 'sub_categories#move_lower', as: :move_lower
          end
          resources :stories, except: %i[index new edit] do
            member do
              patch 'move_higher' => 'stories#move_higher', as: :move_higher
              patch 'move_lower' => 'stories#move_lower', as: :move_lower
            end
            resources :task_points, only: %i[create destroy]
          end
        end
      end
    end
  end

  root :to => 'projects#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="mitsumottaroApp">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "見積もっ太郎" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-target="#menu-items" data-toggle="collapse" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "見積もっ太郎", root_path, class: 'navbar-brand' %>
            </div>
            <div class="collapse navbar-collapse" id="menu-items">
                <ul class="nav navbar-nav">
                    <% if params[:project_id] %>
                        <% unless params[:action] == 'archived' %>
                            <li><%= link_to "TOP", project_dashboard_path(params[:project_id], anchor: "/projects/#{params[:project_id]}/dashboard")  %></li>
                            <li><%= link_to "科目", project_project_tasks_path(params[:project_id]) %></li>
                            <li><%= link_to "追加コスト", project_additional_costs_path(params[:project_id]) %></li>
                        <% else %>
                            <li><%= link_to "TOP", archived_project_dashboard_path(params[:project_id], anchor: "/projects/#{params[:project_id]}/dashboard/archived") %></li>
                        <% end %>
                    <% end %>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            設定
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "科目テンプレート", template_tasks_path %></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; ESTCOSMO Co., Ltd. 2012-2014. This software is distributed under MIT License.</p>
        <iframe src="//ghbtns.com/github-btn.html?user=ESTCOSMO&repo=mitsumottaro&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="95px" height="20px"></iframe>
        <iframe src="//ghbtns.com/github-btn.html?user=ESTCOSMO&repo=mitsumottaro&type=fork&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="95px" height="20px"></iframe>
        <iframe src="//ghbtns.com/github-btn.html?user=ESTCOSMO&type=follow&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="170px" height="20px"></iframe>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>